### ISSUE TITLE
那曲县和嘉黎县的行政区域编码重复

### ISSUE THREAD

**Issue by boolean-dev** [eduosi/district#19]
http://www.gov.cn/test/2011-08/22/content_1930111.htm
根据这里面的显示
那曲县542421
嘉黎县542422
![image](https://user-images.githubusercontent.com/20177406/51662391-a6a4b380-1fee-11e9-81f4-b7820afd24ce.png)
这里显示两个区域是一个行政编码

**Comment by eduosi** [comment]
已更新

**Comment by eduosi** [comment]
谢谢
